# Generated by Django 3.0.7 on 2020-06-07 21:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 21, 56, 42, 40576, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
