# Generated by Django 3.0.7 on 2020-06-10 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200608_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 17, 35, 50, 641961, tzinfo=utc)),
        ),
    ]
