# Generated by Django 3.0.7 on 2020-06-10 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200610_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creation_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 18, 25, 52, 465227, tzinfo=utc)),
        ),
    ]
